name: KYB Verification Reminder (On First Approval - Static Link)

on:
  pull_request_review:
    types: [submitted]

jobs:
  kyb_reminder:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for existing comment
        id: check_for_approvals
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const comments = await github.rest.issues.listComments({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const kyCommentExists = comments.data.some(comment => comment.body.includes('To complete the process, please verify your organization\'s information'));

            if (kyCommentExists) {
                console.log('KYB comment already exists. Skipping.');
                process.exit(1); // Fail the step if comment exists
            }

      - name: Post comment
        # if: always() && needs.check_for_approvals.outcome == 'success'
        # if: success() && needs.check_for_approvals.outcome == 'success'
        if: always() && github.steps.check_for_approvals.outcome == 'success'
        
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const kyb = 'https://in.sumsub.com/idensic/l/#/uni_JRqwo72Y5AjXaRDO';
            const kyc = 'https://in.sumsub.com/idensic/l/#/uni_mjcB05gJZfh8dbr7';

            const message = `👋 Thanks for submitting your application!

            To complete the process, please [verify your organization's information using our [KYB](${kyb}) (in case you're applying as an entity) and [KYC](${kyc}) (in case you are applying as an individual) workflows.

            Please complete this step as soon as possible. If you have any questions, please don't hesitate to ask.`;

            github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
